@Library('Jenkins_shared_library') _

def COLOR_MAP = [
    'FAILURE': 'danger',
    'SUCCESS': 'good'
]

pipeline {
    agent any
    parameters {
        choice(name: 'action', choices: 'create\ndelete', description: 'Select create or destroy.')
    }
    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    deleteDir()
                }
            }
        }

        stage('Checkout from Git') {
            steps {
                script {
                    checkoutGit('https://github.com/damodarddr/youtube-clone-app.git', 'main')
                }
            }
        }
    }
    post {
        always {
            echo 'Slack Notifications'
            script {
                slackSend (
                    channel: '#jenkins-youtube',
                    color: COLOR_MAP[currentBuild.currentResult],
                    message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} \n build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
                )
            }
        }
    }
}
